### ISSUE TITLE
error message at 5-model_analysis.qmd

### ISSUE THREAD

**Issue by jwang-lilly** [maxdrohde/bayesian_ordinal_transition#1]
Max,

 Congratulations on the great tutorial "Bayesian transition models for ordinallongitudinal outcomes". I really enjoyed reading it and tried to follow along using the Violet simulated data.  So far step 1 through 4 ran through perfectly.  At 5-model_analysis.qmd, the following error message was produced.  Any insight is greatly appreciated.

processing file: 5-model_analysis.qmd
  |........................                           |  47% [unnamed-chunk-10]
Quitting from lines 94-109 [unnamed-chunk-10] (5-model_analysis.qmd)
Error in `reformulate()`:
! 'termlabels' must be a character vector of length at least one
Backtrace:
 1. stats::predict(mod, newdata, posterior.summary = "all", type = "lp")
 2. rmsb:::predict.blrm(...)
 3. rms::predictrms(object, ..., type = "x")
 4. rms:::removeFormulaTerms(fit$sformula, which = "offset", delete.response = TRUE)
 5. stats::drop.terms(te, s - ypresent, keep.response = !delete.response)
 6. stats::reformulate(...)
                                                                                                             
Execution halted

**Comment by maxdrohde** [comment]
Hello @JianWang2016 , I'm glad you enjoyed reading our paper!

I re-ran the code, but I cannot reproduce the issue you are having. Have you updated to the latest version of the `rmsb` package on CRAN? If the issue still persists, please let me know and I will look into it more.

Thank you,
Max

**Comment by jwang-lilly** [comment]
Thanks much Max.  That resolved it.
