### ISSUE TITLE
Error while estimating the transition probabilities

### ISSUE THREAD

**Issue by saswata7001998** [maxdrohde/bayesian_ordinal_transition#2]
Hi, I was rerunning the VIOLET example and encountered some errors. I am facing a similar issue in another project while using the same code. I have attached a snapshot of the error message. Kindly help me fix this.
<img width="465" alt="image" src="https://github.com/user-attachments/assets/157ff424-4a33-442d-be32-4962de7fe9c8">

**Comment by maxdrohde** [comment]
@saswata7001998  Could you let me know which version of `rmsb` you have installed?

You can run:

```r
packageVersion("rmsb")
```

**Comment by saswata7001998** [comment]
Version ‘1.1.1’

**Comment by maxdrohde** [comment]
Did you run the Violet example from the beginning by calling `quarto render` from within that folder? It's possible that you may have missed some earlier steps that were necessary for the lines of code that you showed above.

**Comment by maxdrohde** [comment]
If it's an issue with the package or R version, you can use my `renv` lock file here to ensure that you have the same packages and R version as me.

https://gist.github.com/maxdrohde/02c5e0b5a6db86506a720061d08603d3

See here for instructions on how to use `renv` with the lock file: https://rstudio.github.io/renv/articles/collaborating.html

**Comment by saswata7001998** [comment]
Yes, I ran the Violet example by calling quarto render from within that folder. The model itself is running (I can get the model diagnostics as well as model summary), the error is happening while running the predict function.
Sure I will use the lock file, and check

**Comment by saswata7001998** [comment]
Hi i have used the lock file and made sure all packages are same. But unfortunately the problem persists with the predict() function. Actually this method is perfectly suited to the purpose of my ongoing work. Can you provide any other solution to this problem?

**Comment by maxdrohde** [comment]
@saswata7001998  I ran the entire VIOLET analysis from scratch on my MacOS computer and did not run into any errors. Maybe it is an operating system issue?

Could you copy and paste all the output from `devtools::session_info()` in R?

Also, could you include a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the error?

Thanks for helping sort out this issue!

**Comment by saswata7001998** [comment]
Hi @maxdrohde , i reinstalled the R and all the packages. Now its working fine. There are no errors. Probably it was some issue with R.  Thanks a lot for your help.
